### ISSUE TITLE
Create a github release

### ISSUE THREAD

**Issue by Riduidel** [rosenbjerg/wsl2-podman#2]
Scripts seem to be excellently prepared. However, to run them, i have to either git clone or download them raw one by one.
I woul better have a zip archive downloadable from the github releases section.

**Comment by rosenbjerg** [comment]
Hi @Riduidel 
I think the link in the readme is exactly what you seek:
[https://github.com/rosenbjerg/wsl2-podman/archive/refs/heads/main.zip](https://github.com/rosenbjerg/wsl2-podman/archive/refs/heads/main.zip)
Please reopen this issue if that is not the case :)
