### ISSUE TITLE
Podman package not found

### ISSUE THREAD

**Issue by illusive** [rosenbjerg/wsl2-podman#3]
Distro: Ubuntu 20.04.3 LTS (GNU/Linux 5.10.16.3-microsoft-standard-WSL2 x86_64)

Installing podman ..
E: Unable to locate package podman

-----------------------------------------------------------------------------------------------

**Comment by rosenbjerg** [comment]
Podman is now supported on Windows by 1st party!
See their guide [here](https://github.com/containers/podman/blob/main/docs/tutorials/podman-for-windows.md)
